version: '3.7'

networks:
  traefik:
    name: ${NETWORK}
    external: true

services:
  frontend:
    networks:
      - traefik
    labels:
      traefik.http.routers.frontend.rule: Host(`${HOST}`)
      demo.env: ${ENV}
    environment:
      - AUTH_URL
      - API_URL
