version: "3.7"

services:
  frontend:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules # Excludes node_modules
      - npm-cache:/root/.npm
    env_file:
      - ./.env
volumes:
  npm-cache:
    external: false
  node_modules:
