version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - /app/node_modules
      - npm-cache:/root/.npm
volumes:
  npm-cache:
    external: false
  node_modules:
